/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package GitProject

class App {
    val greeting: String
        get() {
            return "Hello world!"
        }
    val someText= "some text"
    val someText1= "some text14"
}

fun main() {
    println(App().greeting)
}
