/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package GitProject

class App {
    val greeting: String
        get() {
            return "Good sdfgsdfgbye world!"
        }
}

fun main() {
    println(App().greeting)
}
